name: Build libavif RPMs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repository files
        run: find . -type f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Print .dockerignore
        run: cat .dockerignore || echo ".dockerignore not found"

      - name: List files in build context
        run: ls -alh .

      - name: Build Docker image for libavif RPM build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: true
          tags: libavif-builder:latest
          progress: plain

      - name: Run rpmbuild inside Docker container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/rpmbuild:/root/rpmbuild" \
            libavif-builder

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libavif-rpms
          path: rpmbuild/RPMS/
