name: Build libavif RPMs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for rpmbuild
        run: docker build -t libavif-builder .

      - name: Run rpmbuild inside Docker container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/rpmbuild:/root/rpmbuild" \
            libavif-builder

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libavif-rpms
          path: rpmbuild/RPMS/
